#!/usr/bin/env ruby

task default: %i[test stones]

desc 'testing alive-ness'
task :test do
  puts "I'm alive"
end

desc 'Install gems'
task :stones do
  puts 'Content of gem-file'
  sh 'cat -n Gemfile'
  sh 'bundle install'
end
