---
# this workflows to check lua syntax error and linting
name: lua-linting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install lua and luacheck
      run: |
        apt update -y ; apt install -y lua luacheck
    - name: Lint with lua
      run: |
        luacheck . --codes
